# Dutch occupational titles for HISCO 92: "Printers And Related Workers"
# endpoint: https://api.druid.datalegend.net/datasets/HistoryOfWork/historyOfWork-all-latest/services/historyOfWork-all-latest/sparql

PREFIX schema: <http://schema.org/>
PREFIX hisco-code: <https://iisg.amsterdam/resource/hisco/code/hisco/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT(?occtitle) ?code WHERE {
  ?code rdfs:subClassOf/rdfs:subClassOf hisco-code:92 .
  ?uri  schema:occupationalCategory ?code ;
        schema:name ?occtitle .
  FILTER (lang(?occtitle) = 'nl')
} ORDER BY ?occtitle
